type: pipeline
description: preprocess-train-test-deploy
compute: azureml:A1v2

jobs:
  preprocess:
    type: command
    component: azureml:preprocess:@latest
    inputs:
      raw_data: azureml:diabetes-dataset@latest
    outputs:
      cleaned_data_path: azureml:cleaned_data_path

  train:
    type: command
    component: azureml:train:2
    inputs:
      training_data: ${{parent.jobs.preprocess.outputs.cleaned_data_path}}
    outputs:
      model_output: azureml:model_output_folder
