type: pipeline
name: preprocess_train_test_deploy
compute: azureml:A1v2

inputs:
  raw_data:
    type: uri_folder

outputs:
  model:
    type: mlflow_model
    mode: upload

jobs:
  preprocess:
    type: command
    component: azureml:preprocess@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      prepared_data: ${{parent.outputs.prepared_data}}

  train:
    type: command
    component: azureml:train@latest
    inputs:
      prepared_data: ${{parent.jobs.preprocess.outputs.prepared_data}}
    outputs:
      model:
        mode: upload
        type: mlflow_model
        path: ${{parent.outputs.model}}
