$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
compute: azureml:DS11v2lp
inputs:
  raw_data:
    type: mltable
    path: azureml:diabetes@latest
jobs:
  train_score_eval:
    type: command
    component: azureml:train_pipeline_component@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      model_output:
        type: mlflow_model
      eval_report:
        type: uri_folder
