experiment_name: diabetes
description: "Simple example to show how model training works in AML"
compute: azureml:A1v2
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu:1
command: >-
  python train.py --training_data ${{inputs.training_data}}
display_name: model-training-diabetes
inputs:
  training_data:
    type: mltable
    path: azureml:diabetes_dataset@latest
