trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'aml-workspace-connection'
  mlWorkspace: 'juicebase-kickoff'
  mlResourceGroup: 'sales-ai'


stages:
- stage: BuildAndDeployComponents
  displayName: 'Build and Deploy AML Components'
  jobs:
  - job: DeployComponents
    displayName: 'Deploy AML Components'
    steps:
    - checkout: self # Ensure your repository is checked out

    - task: AzureCLI@2
      displayName: 'Set Azure ML Default Workspace'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account set --subscription $(azureSubscription)
          az configure --defaults workspace=$(mlWorkspace) group=$(mlResourceGroup)

    - task: AzureCLI@2
      displayName: 'Create Train Model Component'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Ensure your component YAML file path is correct
          az ml component create --file pipeline_components/preprocess.yml

#    - task: AzureCLI@2
#      displayName: 'Create Score Data Component'
#      inputs:
#        azureSubscription: $(azureSubscription)
#        scriptType: 'bash'
#        scriptLocation: 'inlineScript'
#        inlineScript: |
#          az ml component create --file components/score_data.yaml
#
#    - task: AzureCLI@2
#      displayName: 'Create Eval Model Component'
#      inputs:
#        azureSubscription: $(azureSubscription)
#        scriptType: 'bash'
#        scriptLocation: 'inlineScript'
#        inlineScript: |
#          az ml component create --file components/eval_model.yaml
#
#    - task: AzureCLI@2
#      displayName: 'Create Train Pipeline Component'
#      inputs:
#        azureSubscription: $(azureSubscription)
#        scriptType: 'bash'
#        scriptLocation: 'inlineScript'
#        inlineScript: |
#          az ml component create --file components/train_pipeline_component.yaml
#
#
#
#jobs:
#  azureml-job:
#    runs-on: ubuntu-latest
#
#    steps:
#    # Checkout your repo
#    - name: Checkout repository
#      uses: actions/checkout@v4
#
#    # Log in to Azure
#    - name: Azure CLI login
#      uses: azure/login@v1
#      with:
#        creds: ${{ secrets.CONET_AZURE_CREDENTIALS }}
#
#    # Set default subscription and workspace
#    - name: Set Azure defaults
#      run: |
#        az account set --subscription "${{ secrets.CONET_AZURE_SUBSCRIPTION_ID }}"
#        az configure --defaults workspace=${{ secrets.JUICEBASE_AML_WORKSPACE }} group=${{ secrets.AZURE_RESOURCE_GROUP }}
#
#    # Deploy pipeline components
#    - name: Deploy pipeline components
#      run: |
#        az ml component create --file ./pipeline_components/preprocess.yml
#        az ml component create --file ./pipeline_components/train.yml
#        az ml component create --file pipeline.yml --workspace-name
#
##    # Submit the Azure ML job
##    - name: Submit Azure ML job
##      run: |
##        az ml job create --file training_job.yml --workspace-name ${{ secrets.AML_WORKSPACE_NAME }}
