$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
name: train_pipeline_component
display_name: Train Pipeline Component
type: pipeline
description: E2E dummy train-score-eval pipeline with components defined via yaml.

inputs:
  raw_data:
    type: mltable
  training_learning_rate:
    type: number
    description: Learning rate for training
    default: 0.01 # Example default if not provided in Python
  training_max_epochs:
    type: integer
    description: Maximum epochs for training
    default: 20
  learning_rate_schedule:
    type: string
    description: Learning rate schedule
    default: "time-based"

outputs:
  model_output:
    type: mlflow_model
    description: The trained model
  eval_report:
    type: uri_folder
    description: The evaluation report

jobs:
  preprocess:
    type: pipeline
    component: azureml:preprocess@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      training_data:
        mode: rw_mount
      test_data:
        mode: rw_mount

  train_with_sample_data:
    type: pipeline
    component: azureml:train_model@latest # Or a specific version, e.g., azureml:train_model:1
    inputs:
      training_data: ${{parent.jobs.preprocess.outputs.training_data}}
      max_epochs: ${{parent.inputs.training_max_epochs}}
      learning_rate: ${{parent.inputs.training_learning_rate}}
      learning_rate_schedule: ${{parent.inputs.learning_rate_schedule}}
    outputs:
      model_output: ${{parent.outputs.model_output}}

  score_with_sample_data:
    type: pipeline
    component: azureml:score_data@latest # Or a specific version
    inputs:
      model_input: ${{parent.jobs.train_with_sample_data.outputs.model_output}}
      test_data: ${{parent.jobs.preprocess.outputs.test_data}}
    outputs:
      score_output:
        type: uri_folder # Or uri_file
        mode: upload # Translates from .mode = "upload"

  eval_with_sample_data:
    type: pipeline
    component: azureml:eval_model@latest # Or a specific version
    inputs:
      scoring_result: ${{parent.jobs.score_with_sample_data.outputs.score_output}}
    outputs:
      eval_report: ${{parent.outputs.eval_report}}