name: train
display_name: Train Model
type: command
description: Train the logistic regression for Diabetes data
inputs:
  prepared_data:
    type: uri_folder
outputs:
  model:
    type: mlflow_model
    mode: upload
code: ../src/train.py
environment: azureml:diabetes@latest
command: >
  python train.py --cleaned_data_path ${{inputs.prepared_data}}
