name: train
display_name: Train Model
type: command
description: Train the logistic regression for Diabetes data
inputs:
  preprocessed_data:
    type: uri_folder
outputs:
  model_path:
    type: uri_folder
code: ../src
environment: azureml:diabetes@latest
command: >
  python train.py --cleaned_data_path ${{inputs.cleaned_data_path}} --model_path ${{outputs.model_path}}
