$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train_model
display_name: Train Model
description: A dummy training component
inputs:
  training_data: 
    type: mltable
    mode: ro_mount
  max_epochs:
    type: integer
  learning_rate: 
    type: number
    default: 0.01
  learning_rate_schedule: 
    type: string
    default: time-based 
outputs:
  model_output:
    type: uri_folder
  parameter_output:
    type: uri_folder
code: .
environment: azureml:sklearn_juicebase@latest
command: >-
  python train.py 
  --training_data ${{inputs.training_data}} 
  --max_epochs ${{inputs.max_epochs}}
  --learning_rate ${{inputs.learning_rate}} 
  --learning_rate_schedule ${{inputs.learning_rate_schedule}} 
  --model_output ${{outputs.model_output}}
  --parameter_output ${{outputs.parameter_output}}
