name: Trigger Azure ML Job

on:
  push:
    branches:
      - main
  workflow_dispatch: # allow manual trigger too

jobs:
  azureml-job:
    runs-on: ubuntu-latest

    steps:
    # Checkout your repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Log in to Azure
    - name: Azure CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.CONET_AZURE_CREDENTIALS }}

    # Set default subscription and workspace
    - name: Set Azure defaults
      run: |
        az account set --subscription "${{ secrets.CONET_AZURE_SUBSCRIPTION_ID }}"
        az configure --defaults workspace=${{ secrets.JUICEBASE_AML_WORKSPACE }} group=${{ secrets.AZURE_RESOURCE_GROUP }}

    # Deploy pipeline components
    - name: Deploy pipeline components
      run: |
        az ml component create --file ./pipeline_components/preprocess.yml
        az ml component create --file ./pipeline_components/train.yml
        az ml component create --file pipeline.yml --workspace-name

#    # Submit the Azure ML job
#    - name: Submit Azure ML job
#      run: |
#        az ml job create --file training_job.yml --workspace-name ${{ secrets.AML_WORKSPACE_NAME }}
