name: Trigger Azure ML Job

on:
  push:
    branches:
      - main
  workflow_dispatch: # allow manual trigger too

jobs:
  azureml-job:
    runs-on: ubuntu-latest

    steps:
    # Checkout your repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Log in to Azure
    - name: Azure CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Set default subscription and workspace
    - name: Set Azure defaults
      run: |
        az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        az configure --defaults workspace=${{ secrets.AZURE_WORKSPACE }} group=${{ secrets.AZURE_RESOURCE_GROUP }}

    # Submit the Azure ML job
    - name: Submit Azure ML job
      run: |
        az ml job create --file training_job.yml --workspace-name sales-ai-aml-workspace

    # (Optional) Monitor the job
    - name: Monitor Azure ML job
      run: |
        JOB_ID=$(az ml job list --query "[0].name" -o tsv)
        echo "Job ID: $JOB_ID"
        az ml job show --name $JOB_ID
