name: Trigger Azure ML Job

on:
  push:
    branches:
      - main
  workflow_dispatch: # allow manual trigger too

jobs:
  azureml-job:
    runs-on: ubuntu-latest

    steps:
    # Checkout your repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Log in to Azure
    - name: Azure CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.CONET_AZURE_CREDENTIALS }}

    # Set default subscription and workspace
    - name: Set Azure defaults
      run: |
        az account set --subscription "${{ secrets.CONET_AZURE_SUBSCRIPTION_ID }}"
        az configure --defaults workspace=${{ secrets.JUICEBASE_AML_WORKSPACE }} group=${{ secrets.AZURE_RESOURCE_GROUP 
        

    - name: Deploy pipeline components
      run: |
        az ml component create --file ./components/preprocess/preprocess.yml
#        az ml component create --file ./components/train/train.yml
#        az ml component create --file ./components/score/score.yml
#        az ml component create --file ./components/eval/eval.yml
#        az ml component create --file ./components/compare2/compare2.yml
#        az ml component create --file ./components/train_score_eval/train_score_eval.yml
        az ml batch-endpoint create --file batch-endpoint.yml --debug
#        az ml batch-deployment create --file batch-deployment.yml --debug
#        az ml batch-endpoint update --name training-pipeline-endpoint --set default_deployment=training-pipeline-deployment --debug
